<?php

namespace ContainerSLm9vtc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KxSUNCOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KxSUNCO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KxSUNCO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paramFetcher' => ['privates', '.errored..service_locator.KxSUNCO.FOS\\RestBundle\\Request\\ParamFetcher', NULL, 'Cannot autowire service ".service_locator.KxSUNCO": it references class "FOS\\RestBundle\\Request\\ParamFetcher" but no such service exists. Try changing the type-hint to "FOS\\RestBundle\\Request\\ParamFetcherInterface" instead.'],
        ], [
            'paramFetcher' => 'FOS\\RestBundle\\Request\\ParamFetcher',
        ]);
    }
}
