<?php

namespace ContainerSLm9vtc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateArticleControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Article\CreateArticleController' shared autowired service.
     *
     * @return \App\Controller\Article\CreateArticleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Article/CreateArticleController.php';

        return $container->services['App\\Controller\\Article\\CreateArticleController'] = new \App\Controller\Article\CreateArticleController(($container->services['.container.private.form.factory'] ?? $container->load('get_Container_Private_Form_FactoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Security\\UserResolver'] ?? $container->load('getUserResolverService')));
    }
}
