<?php

namespace ContainerSLm9vtc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteCommentControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Comment\DeleteCommentController' shared autowired service.
     *
     * @return \App\Controller\Comment\DeleteCommentController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Comment/DeleteCommentController.php';

        return $container->services['App\\Controller\\Comment\\DeleteCommentController'] = new \App\Controller\Comment\DeleteCommentController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
