<?php

namespace ContainerSLm9vtc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteArticleControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Article\DeleteArticleController' shared autowired service.
     *
     * @return \App\Controller\Article\DeleteArticleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Article/DeleteArticleController.php';

        return $container->services['App\\Controller\\Article\\DeleteArticleController'] = new \App\Controller\Article\DeleteArticleController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
