<?php

namespace ContainerSLm9vtc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetTagsListControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Tag\GetTagsListController' shared autowired service.
     *
     * @return \App\Controller\Tag\GetTagsListController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Tag/GetTagsListController.php';

        return $container->services['App\\Controller\\Tag\\GetTagsListController'] = new \App\Controller\Tag\GetTagsListController(($container->privates['App\\Repository\\TagRepository'] ?? $container->load('getTagRepositoryService')));
    }
}
