<?php

namespace ContainerSLm9vtc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetArticlesFeedControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Article\GetArticlesFeedController' shared autowired service.
     *
     * @return \App\Controller\Article\GetArticlesFeedController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Article/GetArticlesFeedController.php';

        return $container->services['App\\Controller\\Article\\GetArticlesFeedController'] = new \App\Controller\Article\GetArticlesFeedController(($container->privates['App\\Repository\\ArticleRepository'] ?? $container->load('getArticleRepositoryService')), ($container->privates['App\\Security\\UserResolver'] ?? $container->load('getUserResolverService')));
    }
}
