<?php

namespace ContainerSLm9vtc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetProfileControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Profile\GetProfileController' shared autowired service.
     *
     * @return \App\Controller\Profile\GetProfileController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Profile/GetProfileController.php';

        return $container->services['App\\Controller\\Profile\\GetProfileController'] = new \App\Controller\Profile\GetProfileController();
    }
}
