<?php

namespace ContainerSLm9vtc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetArticlesListControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Article\GetArticlesListController' shared autowired service.
     *
     * @return \App\Controller\Article\GetArticlesListController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Article/GetArticlesListController.php';

        return $container->services['App\\Controller\\Article\\GetArticlesListController'] = new \App\Controller\Article\GetArticlesListController(($container->privates['App\\Repository\\ArticleRepository'] ?? $container->load('getArticleRepositoryService')));
    }
}
