<?php

namespace ContainerSLm9vtc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetOneArticleControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Article\GetOneArticleController' shared autowired service.
     *
     * @return \App\Controller\Article\GetOneArticleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Article/GetOneArticleController.php';

        return $container->services['App\\Controller\\Article\\GetOneArticleController'] = new \App\Controller\Article\GetOneArticleController();
    }
}
