<?php

namespace ContainerSLm9vtc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJWTAuthenticationSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\JWTAuthenticationSubscriber' shared autowired service.
     *
     * @return \App\EventListener\JWTAuthenticationSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/JWTAuthenticationSubscriber.php';

        return $container->privates['App\\EventListener\\JWTAuthenticationSubscriber'] = new \App\EventListener\JWTAuthenticationSubscriber(($container->privates['App\\Serializer\\Normalizer\\UserNormalizer'] ?? $container->load('getUserNormalizerService')));
    }
}
