<?php

namespace ContainerSLm9vtc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParamFetcherService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KxSUNCO.FOS\RestBundle\Request\ParamFetcher' shared service.
     *
     * @return \FOS\RestBundle\Request\ParamFetcher
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.KxSUNCO": it references class "FOS\\RestBundle\\Request\\ParamFetcher" but no such service exists. Try changing the type-hint to "FOS\\RestBundle\\Request\\ParamFetcherInterface" instead.');
    }
}
