<?php

namespace ContainerSLm9vtc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnfavoriteArticleControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Article\UnfavoriteArticleController' shared autowired service.
     *
     * @return \App\Controller\Article\UnfavoriteArticleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Article/UnfavoriteArticleController.php';

        return $container->services['App\\Controller\\Article\\UnfavoriteArticleController'] = new \App\Controller\Article\UnfavoriteArticleController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Security\\UserResolver'] ?? $container->load('getUserResolverService')));
    }
}
