<?php

namespace ContainerSLm9vtc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\UserResolver' shared autowired service.
     *
     * @return \App\Security\UserResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Security/UserResolver.php';

        return $container->privates['App\\Security\\UserResolver'] = new \App\Security\UserResolver(($container->services['security.token_storage'] ?? $container->getSecurity_TokenStorageService()));
    }
}
