<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSLm9vtc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSLm9vtc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSLm9vtc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSLm9vtc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSLm9vtc\App_KernelDevDebugContainer([
    'container.build_hash' => 'SLm9vtc',
    'container.build_id' => '8969708e',
    'container.build_time' => 1607584885,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSLm9vtc');
